language: java
sudo: true
dist: trusty
jdk: oraclejdk9
cache:
  directories:
    - "$HOME/.m2"
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw

deploy:
  provider: heroku
  api_key:
    secure: "1cfbdb5f-83a5-4e49-b165-1ad1a15554a0"
      app: diplom-altstu
  on: dev